apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: ${{ .Values.name }}
    monitor: application
  name: ${{ .Values.name }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: ${{ .Values.name }}